-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Gép: 127.0.0.1
-- Létrehozás ideje: 2024. Jan 08. 11:46
-- Kiszolgáló verziója: 10.4.28-MariaDB
-- PHP verzió: 8.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Adatbázis: `receptekadatb`
--

-- --------------------------------------------------------

--
-- Tábla szerkezet ehhez a táblához `etelek`
--

CREATE TABLE `etelek` (
  `etelek_id` int(11) NOT NULL,
  `etelek_nev` varchar(255) NOT NULL,
  `etelek_tipus` int(11) NOT NULL,
  `etelek_kep` varchar(255) NOT NULL,
  `etelek_hozzavalok` varchar(255) NOT NULL,
  `etelek_allergenek` varchar(255) NOT NULL,
  `etelek_elkeszites` text NOT NULL,
  `etelek_video` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_hungarian_ci;

--
-- A tábla adatainak kiíratása `etelek`
--

INSERT INTO `etelek` (`etelek_id`, `etelek_nev`, `etelek_tipus`, `etelek_kep`, `etelek_hozzavalok`, `etelek_allergenek`, `etelek_elkeszites`, `etelek_video`) VALUES
(1, 'Sült paradicsom', 1, 'kep1.jpg', '1ek - olívaolaj	\r\n0.5kg - koktélparadicsom	\r\nsó	\r\nbors	\r\n10gerezd - fokhagyma	\r\n1tk - rozmaring	\r\n3tk - kakukkfű	\r\n10levél - bazsalikom', 'nincs', '1. A sütőt előmelegítjük 180 fokra.\r\n2. Egy tepsibe olívaolajat öntünk, erre rakjuk a megmosott paradicsomokat, sózzuk, borsozzuk, a paradicsomok közé rakjuk a héjas fokhagymagerezdeket. Ezek sütés közben kellemesen aromásítják majd a paradicsomot, sütés után kinyomkodjuk a héjából, kellemes édeskés, krémes állagú lesz.\r\n3. A paradicsomokat fűszerezzük rozmaringgal, kakukkfűvel, az egészet kicsit összefogatjuk, majd az előmelegített sütőbe rakjuk 30-35 percre, amíg a paradicsom héja enyhén megsül, és a húsa kissé összeesik.\r\n4. Az elkészült paradicsomokra friss bazsalikomleveleket tépkedünk, és hagyjuk langyosra hűlni.\r\n5. A sült paradicsomot tehetjük pirítósra, kínálhatjuk húsok mellé. de hozzáadhatjuk készülő fogásokhoz is.', 'https://www.youtube.com/embed/MDqcv5ZwtRw?si=f8YIb_pwsPfAyWfI'),
(2, 'Krémsajtos tojássaláta', 1, 'kep2.jpg', '4db - főtt tojás	\r\n1doboz - natúr krém sajt	\r\n2tk - dijoni magos mustár	\r\n1fej - lila hagyma	\r\n1csok - petrezselyemzöld	\r\nsó	\r\n2csip - őrölt fehérbors	', '- tojás\r\n- tej\r\n- mustár', '1. A kis fej lila hagymát és a kis csokor petrezselyemzöldet apróra felvágjuk.\r\n2. Az előzőleg megfőtt tojásokat felkockázzuk.\r\n3. A krémsajthoz hozzákeverjük a mustárt, az apróra vágott lila hagymát, petrezselyemzöldet és összekeverjük. Ízlés szerint sózzuk és borsozzuk.\r\n4. A keverékhez hozzáadjuk a felkockázott főtt tojást és óvatosan összeforgatjuk.\r\n5. Tálalásig hűtőben pihentetjük.', 'https://www.youtube.com/embed/fSzTnhEENxA?si=R89-QY69h30gZ-Yg'),
(3, 'Csikós tokány', 2, 'kep3.jpg', '15dkg - füstölt kenyér szalonna	\r\n2fej - vöröshagyma	\r\n2db - t. v. paprika	\r\nbors	\r\n80dkg - szeletelt sertéslapocka	\r\nsó	\r\n3gerezd - fokhagyma	\r\n1ek - pirospaprika	\r\n1db - paradicsom	\r\n2ek - tejföl	\r\n1ek - liszt', '- glutén\r\n- tej', '1. A szalonnát 3-4 milliméteresre csíkozzuk; a hagymát meghámozzuk, felkockázzuk; a paprikát megmossuk, felszeleteljük, majd a hagymához hasonló méretűre vágjuk; a hússzeleteket enyhén átlósan7-8 milliméteres csíkokra vágjuk; a fokhagymát megpucoljuk, apróra vágjuk; végül a paradicsomot is megmossuk, és felkockázzuk.\r\n2. Egy magas falú serpenyőben a szalonnát alacsony fokozaton, időnként kevergetve pár perc alatt átlátszóra pirítjuk, ezután hozzáadjuk a vöröshagymát, és együtt tovább dinszteljük. Hozzáadjuk a paprikát is, megborsozzuk, és addig pároljuk, amíg az alap opálosan áttetsző nem lesz.\r\n3. Ezután hozzáadjuk a tokányhúst, sózzuk, de csak óvatosan, mert a szalonna is sós, és fehéredésig pirítjuk. Ízesítjük a fokhagymával, majd fűszerezzük a pirospaprikával, alaposan elkeverjük, és a kockázott paradicsomot is beletesszük. Ezzel is jól elkeverjük, és felöntjük annyi vízzel, amennyi éppen ellepi, majd lefedjük, és takaréklángon nagyjából 60-70 perc alatt puhára pároljuk.\r\n4. Ha megpuhult, egy kis tálba kanalazzuk a tejfölt, hozzáadjuk a lisztet, és habverő segítségével csomómentesre keverjük, majd hőkiegyenlítéssel a raguhoz öntjük. Pár percig kevergetve készre főzzük a tokányt.\r\n5. Melegen, általában nokedlivel vagy tésztával, esetleg rizzsel és savanyúsággal fogyaszthatjuk ezt a szaftos-ízes megunhatatlan ősi ragut.', 'https://www.youtube.com/embed/JA8jqD-yJDw?si=gGNySX9u7XlXC_Fe'),
(4, 'Margó torony', 4, 'kep4.jpg', '0dkg - darált háztartási keksz	\r\n20dkg - darált dió	\r\n10dkg - sütőmargarin	\r\n20dkg - porcukor	\r\n0.5dl - rum	\r\n3ek - cukrozatlan kakaópor', '- glutén\r\n- diófélék', '1. A darált kekszet a dióval, a porcukorral, a margarinnal, a rummal és a kakaóporral összedolgozuk. A kókuszgolyóhoz hasonló állagot kell kapnunk. Ha esetleg száraz lenne, és nem állna össze, cseppenként adjunk hozzá tejet.\r\n2. A masszát porcukorral megszórt margó torony formába nyomkodjuk majd kiütögetjük. Minden töltés előtt érdemes megporcukrozni a forma belsejét. Ha nincs ilyen formánk, akkor kézzel is formázhatunk a masszából kúpokat. Porcukorral meghintve tálaljuk.', 'nincs'),
(5, 'Finom görögsaláta', 5, 'kep5.jpg', '1db - kígyóuborka	\r\n1fej - lila hagyma	\r\n25dkg - koktélparadicsom	\r\n10dkg - olajbogyó	\r\n15dkg - feta  sajt	\r\n1db - citrom	\r\n3ek - extraszűz olívaolaj	\r\n1tk - szárított bazsalikom	\r\n3tk - szárított oregánó', '- tej\r\n', '1. Előkészítjük a saláta hozzávalóit: az uborkát feldaraboljuk, majd nagyjából egycentis kockákra vágjuk, a hagymát vékonyan felszeleteljük, a koktélparadicsomokat és az olajbogyókat félbevágjuk, a feta sajtot felkockázzuk.\r\n2. Összeállítjuk az öntetet: a citromot félbevágjuk, a levét kinyomjuk, és egy keverőtálba öntjük. Hozzáadjuk az olívaolajat, fűszerezzük a bazsalikommal és az oregánóval, majd jó alaposan egyneműre keverjük.\r\n3. Következhet a saláta összeállítása: salátástálba öntjük az uborkát, a paradicsomot, a lila hagymát, az olajbogyót, végül a feta sajtot. Ráöntjük az öntetet, és alaposan összeforgatjuk, ügyelve, hogy ne törjük össze a sajtot, de az öntetből mindenhova jusson.\r\n4. Az elkészült salátát fogyasztás előtt letakarva egy óráig hűtőben tároljuk. ', 'https://www.youtube.com/embed/8rUZC7ZOplo?si=f2oGLnFEjZPhni_A'),
(6, 'Babgulyás', 3, 'kep6.jpg', '1fej - hagyma	\r\nolaj	\r\n1db - paprika	\r\n1db - paradicsom	\r\n40dkg - sertés comb vagy lapocka	\r\nőrölt - piros paprika	\r\nsó	\r\nételízesítő	\r\n20dkg bab	\r\n4db sárgarépa	\r\n2db petrezselyem gyökér	\r\n4köz burgonya', 'nincs', '1. A felkockázott vöröshagymát olajon megpirítjuk, ezután hozzáadjuk a felkockázott paprikát és paradicsomot majd ezeket összepirítjuk. Mikor szépen összefonnyadtak a hozzávalók, hozzáadjuk a felkockázott húst, megszórjuk őrölt piros paprikával, sóval, ételízesítővel és összeforgatjuk.\r\n2. Ezután hozzáadjuk a babot, felöntjük vízzel és felforraljuk. Forrás után a levesbe tesszük a megtisztított,felkockázott répát, petrezselyem gyökeret és a burgonyát. A levest addig főzzük, ameddig a hús és a bab puha nem lesz.', 'https://www.youtube.com/embed/9T_yaLxH_gY?si=kbxBSgNUsod4YLyp'),
(7, 'Linzerkarika', 4, 'kep7.jpg', '30dkg - liszt	\r\n20dkg - vaj	\r\n1db - tojássárgája	\r\n10dkg - porcukor	\r\n0.5db - citrom reszelt héja	\r\n1db - tojás a kenéshez	\r\n', '- glutén\r\n- tojás\r\n- tej', '1. A linzerkarika elkészítéséhez a lisztet egy tálba öntjük, hozzáadjuk a vajat és összemorzsoljuk. Beleöntjük a tojássárgáját, a porcukrot és a reszelt citromhéjat és gyors mozdulatokkal összegyúrjuk. Gombóccá formáljuk a tésztát és folpakba csomagolva legalább 1 órára a hűtőbe tesszük.\r\n2. A tésztát lisztezett felületen kinyújtjuk és különböző formákat szaggatunk ki belőle. A felének a közepét egy kisebb kiszúróval kilyukasztjuk.\r\n3. Sütőpapírral kibélelt tepsibe tesszük a formákat, a lyukas közepűeket megkenjük tojással. A linzer karikákat 170 fokra előmelegített sütőben 20-25 perc alatt aranybarnára sütjük. Ha megsült ízlés szerint lekvárral, krémmel megtöltjük.', 'https://www.youtube.com/embed/bsLQ1Si2tV8?si=PV9BP9fYVRtjBPvK'),
(8, 'Gazpacho', 3, 'kep8.jpg', '5db - paradicsom	\r\n1db - kígyóuborka	\r\n1db - kaliforniai paprika	\r\n1k - fej vöröshagyma	\r\n2gerezd	- fokhagyma	\r\n0.5db - citrom leve	\r\n1tk - fehérborecet	\r\n2ek - extraszűz olívaolaj	\r\nsó	\r\nbors	\r\n1dl - víz	\r\n1szelet - kenyér	', '- glutén', '1. Előkészítjük az alapanyagokat. A paradicsomok végét x alakban bevágjuk, forrásban lévő vízbe rakjuk 1-2 percre, majd szűrőkanál segítségével áttesszük jéghideg vízbe, ezután meghámozzuk, félbevágjuk, ha szükséges, kivágjuk a csumáját, és rusztikus darabokra vágjuk. Az uborkát meghámozzuk, felkockázzuk. A paprikát megmossuk, kicsumázzuk, ezt is nagyobb darabokra vágjuk. A hagymát meghámozzuk, nagyobb darabokra vágjuk, a fokhagymát szintén meghámozzuk, félbevágjuk.\r\n2. Elővesszük a turmixgépet, és ebbe halmozzuk az előkészített hozzávalókat, a paradicsomot, az uborkát, a paprikát, és a hagymákat. Ízesítjük citromlével, és az ecettel, ráöntjük az olajat, sózzuk, borsozzuk, hozzáadjuk a vizet, majd a tetejére tépkedjük a kenyérszeletet. Ha mindent beleraktunk, lefedjük a turmixgépet, és 5-6 percig erős fokozaton homogénre turmixoljuk a hozzávalókat.\r\n3. Az elkészült levest akár le is szűrhetjük, vagy hagyhatjuk ebben az állapotában is. Hűtőbe rakjuk 4-5 órára, majd hidegen szervírozzuk.\r\n4. Ha azonnal szeretnénk fogyasztani, dolgozzunk hideg zöldségekkel, vagy turmixolás előtt adhatunk jégkockát is az alapanyagokhoz.\r\n5. Ez a spanyol leves a nyár legüdítőbb, legfrissítőbb levesei közé tartozik, könnyen elkészíthető, nem igényel főzést, hosszú ideig friss marad a hűtőben. Tálalhatjuk magában vagy apróra vágott hagymával, paprikával és uborkával, de tehetünk rá pirított kenyérkockát is.', 'https://www.youtube.com/embed/rrY-m3MxliE?si=nEjXnXnHFm3_bDly'),
(9, 'Majonézes kukoricasaláta', 5, 'kep9.jpg', '4ek - majonéz	\r\n1ek - mustár	\r\n2ek - tejföl	\r\n1fej - vöröshagyma	\r\n1db - kukoricakonzerv	\r\nsnidling	', '- tojás\r\n- tej\r\n- mustár', '1. A majonézt kikeverjük a mustárral és a tejföllel, beletesszük a nagyon finomra vágott hagymát és a lecsepegtetett kukoricát. Ízlés szerint megszórjuk felaprított snidlinggel.\r\n2. Összekeverjük, és néhány órát a hűtőben pihentetjük, hogy összeérjenek az ízek. Sült húsokhoz kínáljuk köretként. ', 'https://www.youtube.com/embed/wic6rpVp_7w?si=OH_swcRCbV5jxXRl'),
(10, 'Csirkemellpaprikás', 2, 'kep10.jpg', '1ek - zsír	\r\n1fej - vöröshagyma	\r\ncsip - só	\r\n80dkg - csirkemell	\r\ncsip - bors	\r\n2gerezd - fokhagyma	\r\n1dl - száraz fehérbor	\r\n2db paprika	\r\n1ek pirospaprika	\r\n1db paradicsom	\r\n1dl tejszín	\r\n1ek tejföl', '- tej', '1. Előkészítjük az alapanyagokat: a vöröshagymát meghámozzuk, apróra kockázzuk; a csirkemellet nagyjából kétcentis kockákra vágjuk; a paprikát és a paradicsomot megmossuk, a paprikát felszeleteljük, majd félcentis darabokra vágjuk (így nem lesz darabos a szaft), a paradicsomot apróra kockázzuk; végül a fokhagymagerezdeket meghámozzuk, apróra vágjuk.\r\n2. Egy serpenyőben közepes lángon zsiradékot hevítünk, erre rakjuk a vöröshagymát, enyhén sózzuk, hogy könnyebben kiengedje a nedvességét. Ha kissé üveges, hozzáadjuk a csirkemellkockákat, együtt pirítjuk tovább, közben ízesítjük sóval, borssal.\r\n3. Ha kifehéredtek a húsok, hozzáadjuk a fokhagymát, tovább pároljuk pár percig, majd felöntjük a fehérborral. Ha az alkohol elpárolgott, hozzáadjuk a paprikát, elkeverjük, majd megszórjuk a pirospaprikával, ezt is alaposan elkeverjük. Következik a paradicsom, végül felöntjük egy kevés vízzel, majd lefedve, alacsony hőmérsékleten nagyjából fél óra alatt készre pároljuk.\r\n4. Ha a hús megpuhult, és a szaft is kissé besűrűsödött, hozzáöntjük a tejszínt, majd belekanalazzuk a tejfölt, elkeverjük, és még egyet forralunk rajta.\r\n5. Nokedlivel és savanyúsággal tálaljuk.', 'https://www.youtube.com/embed/DctsPFd0cMA?si=Z77T9svHrCjx2trj'),
(11, 'Pulled pork', 2, 'kep11.jpg', '1.4kg - sertéscomb	\r\n2ek - só	\r\n1tk - őrölt fekete bors	\r\n2tk - majoránna	\r\n2tk - oregano	\r\n1tk - köménymag	\r\n0.5tk - fahéj	\r\n2tk - római kömény	\r\n2tk - őrölt koriander	\r\n1ek - fokhagymapor	\r\n2tk - pirospaprika	\r\n2ek - barna cukor	\r\n1ek - sűrített paradic', '- glutén\r\n- szójabab\r\n- tej', '1. Egy nagy méretű keverőtálban, amibe a hús is elfér, összeállítjuk a pácot. Beletesszük a sót, az őrölt fekete borsot, a majoránnát, az oregánót, a köménymagot, a fahéjat, a római köményt, az őrölt koriandert, a fokhagymaport, a pirospaprikát és a barna cukrot. Hozzákanalazzuk a sűrített paradicsomot, felöntjük olajjal és az egészet jó alaposan összekeverjük.\r\n2. A húst a pácba helyezzük, jól bedörzsöljük a páccal, hogy mindenhol bevonja a felületét.\r\n3. A sütőt 130 Celsius-fokra előmelegítjük.\r\n4. Egy hőálló, vastag falú edényben közepes lángon olajat hevítünk, ebbe tesszük a páccal bekent húst és minden oldalát körbepirítjuk. Hozzáadjuk a megtisztított és cikkekre vágott vöröshagymát, a maradék pácot és beletesszük a ketchupot, a narancslevet, a Worcestershire-szószt, a szójaszószt, a balzsamecetet és a kevés vizet. Jól elkeverjük és felforraljuk. Ha felforrt, lefedjük és az előmelegített sütőbe tesszük 4 órára.\r\n5. Az elkészült húst villával szálaira bontjuk, összekeverjük a szafttal és szendvicsben vagy hot dog kiflibe töltve tálaljuk. A szendvicsbe kerülhet Cheddar sajt, szósz és karikára vágott csemegeuborka is.', 'https://www.youtube.com/embed/ijsJ2l9yqCc?si=7aEDkmrQWyAoPM8V'),
(12, 'Bruschetta', 1, 'kep12.jpg', '8szelet - rozskenyér	\r\n4db - paradicsom	\r\n1k - fej fehér hagyma	\r\n3gerezd - fokhagyma	\r\n1levél - friss oregánó	\r\n1levél - bazsalikom	\r\nsó	\r\nőrölt - fekete bors	\r\n2ek - extra szűz olívaolaj', '- glutén', '1. A paradicsomokat, a hagymát és a zöldfűszereket apróra vágjuk. A fokhagymát lereszeljük.\r\n2. A paradicsomot összekeverjük a bazsalikommal és az oregánóval. Megsózzuk, megborsozzuk, majd meglocsoljuk az olívaolajjal.\r\n3. A kenyerek mindkét oldalát megpirítjuk, és ráhalmozzuk a fűszeres paradicsomot. Szórhatunk a tetejére aprított mozzarella sajtot is. Frissen kínáljuk.', 'https://www.youtube.com/embed/L4ZI32QfGbc?si=Kx4IgFzaOqxh3sYH'),
(13, 'Körtés-pudingos pite', 4, 'kep13.jpg', 'A tésztához:\r\n30dkg - liszt	\r\n15dkg - porcukor	\r\nsó	\r\n12dkg - hideg vaj	\r\n1db - tojás	\r\n1ek - tejföl	\r\n1tk - sütőpor\r\n	\r\nA töltelékhez:\r\n2db - tojás	\r\n4dkg - cukor	\r\n1csom - vaníliás cukor	\r\nsó	\r\n2dl - tej	\r\n2dl - tejszín	\r\n2csom - vaníliaízű pudingpor	\r\n', '- glutén\r\n- tojás\r\n- tej', '1. Egy keverőtálba szórjuk a lisztet, a porcukrot, egy csipet sót, majd hozzáadjuk a felkockázott hideg vajat, a tojást, a tejfölt és a sütőport. Gyors, morzsoló mozdulatokkal elkeverjük a vajat a lisztes keverékkel, és az egészből tésztát gyúrunk. Ha esetleg nedves a tészta, kevés lisztet adjunk még hozzá. Mindenképpen dolgozzunk gyorsan, hogy a vaj ne olvadjon el. A tésztát folpakba csomagoljuk, és fél órára hűtőbe tesszük pihenni, hogy a vaj visszahűljön.\r\n2. Amíg a tészta pihen, elkészítjük a tölteléket. Egy keverőtálba rakjuk a tojásokat, a cukrot, a vaníliás cukrot, egy csipet sót, és jól elkeverjük. Hozzáöntjük a tejet és a tejszínt, ezt is elkeverjük, majd hozzáadjuk a vaníliás pudingport is. Jó alaposan összekeverjük, hogy a pudingpor feloldódjon, majd felhasználásig félretesszük.\r\n3. A körtét megmossuk, meghámozzuk, a magházat és a szárát eltávolítjuk, cikkekre vágjuk, és 2-3 centis darabokra aprítjuk, majd egy tálba tesszük, meglocsoljuk a citrom levével, fűszerezzük fahéjjal és kardamomommal, majd felhasználásig ezt is félretesszük.\r\n4. Előveszünk egy 24 centiméteres torta- vagy piteformát, az aljára sütőpapírt helyezünk. A lehűlt tésztát kicsomagoljuk, a tortaformába rakjuk, és kézzel elegyengetjük a formában úgy, hogy egyenletes, szép kört kapjunk, és pereme is legyen. (Ezt a műveletet nyújtófával is elvégezhetjük, úgy, hogy 2-3 milliméter vastagra nyújtjuk a tésztát, majd a nyújtófára feltekerve a formába igazítjuk.)\r\n5. A sütőt előmelegítjük 180 fokra. A pitealapot villával megszurkáljuk, sütőpapírt helyezünk rá, majd sütőgyöngyöt, vagy ha nincsen, szárazbabot, lencsét vagy rizst. Erre azért van szükség, hogy az elősütés során a pite oldala ne boruljon be, és a közepe ne emelkedjen fel. A tésztát a sütőbe rakjuk 10 percre, azután kivesszük, eltávolítjuk a nehezéket a sütőpapírral együtt, és hagyjuk langyosra hűlni.\r\n6. Az elősütött pitealapot megkenjük a baracklekvárral. Ha a lekvárt egyenletesen eloszlatjuk, a pite alján betömjük a villával okozott lukakat, így nem folyik ki majd a sodó, emellett kiváló ízt ad majd a pitének. A lekváros felületre kanalazzuk a körtedarabokat, majd az egészet felöntjük annyi sodóval, amennyi még nem teljesen lepi el a körtét.\r\n7. A tetejét megszórjuk a szeletelt mandulával, és a sütőbe rakjuk kb. 30 percre, amíg a töltelék megszilárdul, és a teteje enyhén pirosra sül. Az elkészült pitét hagyjuk langyosra hűlni, ezután szeleteljük. Igazi nyár végi, ősz eleji könnyű desszert, csodás fűszeres ízekkel. Egyszerűen kihagyhatatlan.', 'https://www.youtube.com/embed/lFLYHpr4T2A?si=gGMDJkLbhz84l9K3'),
(14, 'Tojásleves', 3, 'kep14.jpg', '2ek - liszt	\r\n2ek - olaj	\r\n2db - babérlevél	\r\n1kvk - őrölt kömény	\r\nsó	\r\n1kvk - őrölt paprika	\r\n6db - tojás	\r\n1ek - ecet	', '- glutén\r\n- tojás', '1. A tojásleves elkészítéséhez alacsony lángon a lisztből és az olajból rántást készítünk, majd felöntjük 1 liter vízzel. Ízesítjük babérlevélel, a köménnyel, egy kevés sóval és az őrölt paprikával.\r\n2. Felverünk kettő tojást, majd ha felforrt a leves, a felvert tojásokat óvatosan belekeverjük, és így még 1-2 percig főzzük.\r\n3. A többi tojást egyenként felütjük, és óvatosan a forró levesbe engedjük. Azután tovább főzzük még így 2-3 percig. Tálalásnál egy tányérba egy bevert tojást teszünk. ', 'https://www.youtube.com/embed/LQ8vWWCMI1g?si=tK8IWZjka4IijYH6'),
(15, 'Majonézes krumplisaláta', 5, 'kep15.jpg', '1.5kg - burgonya	\r\nsó	\r\n2db - lila hagyma	\r\n1db - vöröshagyma\r\n	\r\nA salátaöntethez:\r\n2ek - cukor	\r\n0.5dl - ecet	\r\n1l - víz\r\n	\r\nA majonézhez:\r\n2db - tojás	\r\n1ek - mustár	\r\n3dl - olaj	\r\nsó	\r\nbors	\r\n0.25db - citrom leve	\r\nporcukor	\r\n2dl - tejföl', '- tojás\r\n- tej\r\n- mustár', '1. A burgonyát héjában, sós vízben megfőzzük. A héját még melegen lehúzzuk, lehűtjük, a krumplikat felkarikázzuk. A lila- és a vöröshagymát vékony karikákra vágjuk.\r\n2. Kb. 1 liter cukros, ecetes salátalevet készítünk ízlés szerint ízesítve. A salátalébe tesszük a felkarikázott burgonya- és hagymaszeleteket, kb. 2-3 órát állni hagyjuk, ez idő alatt elkészítjük a majonézt.\r\n3. A majonézhez a tojássárgákat a mustárral kikeverjük, majd az olajat lassan, szinte csepegtetve adagoljuk hozzá, folyamatos keverés mellett. Ízesítjük még sóval, borssal, citromlével és a porcukorral. Ha elkészült, hozzáadjuk a tejfölt.\r\n4. A krumplit és a hagymát alaposan leszűrjük, és egy tálba tesszük. Az elkészült mártással alaposan és óvatosan elverjük, hogy ne törjön össze a burgonya. Ha szükséges, még utólag ízesíthetjük sóval, borssal, és néhány órát még a hűtőben pihentetjük, hogy az ízek jól összeérjenek. ', 'https://www.youtube.com/embed/8rxKy-uA6K8?si=OBO0ATbBgconP4pd'),
(16, 'Cobb saláta', 5, 'kep16.jpg', '8db - koktélparadicsom	\r\n1fej - római saláta	\r\n4db - tojás	\r\n8szelet - bacon	\r\n40dkg - csirke	\r\n0.33csésze - vörösborecet	\r\n0.66csésze - olívaolaj	\r\n1ek - dijoni mustár	\r\nsó	\r\nfekete bors (őrölt)	\r\n1db - avokádó	\r\n10dkg - kék sajt', 'nincs', '1. A paradicsomokat félbe vágjuk. A római salátát  közepes darabokra tépkedjük. A tojásokat keményre főzzük, majd miután megpucoltuk, negyedeljük őket. A bacont ropogósra sütjük, miközben a főtt csirkét apróra kockázzuk.\r\n2. Az ecetet, az olajot és a mustárt egy edényben összekeverjük, sózzuk, borsozzuk.\r\n3. Egy nagyobb lapos tányér aljára szórjuk a salátát, majd a tojásból, a paradicsomból, a csirkéből, az avokádó szeletekből, a szalonnából és a kék sajtból rakjunk ki egységes sorokat. Végül leöntjük az elkészült salátaöntettel.', 'https://www.youtube.com/embed/nZSVWK00GtY?si=_FFtWs6IKTe0Wo_c'),
(17, 'Harcsaleves', 3, 'kep17.jpg', '60dkg - afrikaiharcsa-filé	\r\n20dkg - vöröshagyma	\r\n10dkg - burgonya	\r\n10dkg - paradicsom	\r\n10dkg - tv-paprika	\r\n5dkg - olívabogyó	\r\n5dkg - kapribogyó	\r\n5dkg - gyöngyhagyma	\r\n0.5dl - olaj	\r\nőrölt - fűszerpaprika	\r\nőrölt - fekete bors	\r\nsó	', '- hal', '1. A harcsaleves elkészítéséhez a felaprított vöröshagymát egy kevés olajon megfonnyasztjuk, majd hozzáadjuk a kockára vágott burgonyát és a felaprított paradicsomot és paprikát. Ízesítjük, fűszerezzük sóval, borssal és fűszerpaprikával.\r\n2. Ezután felengedjük vízzel, majd belehelyezzük az előre sóval és borssal fűszerezett, felkockázott afrikai harcsát. Hozzáadjuk az olívabogyót, a gyöngyhagymát és a kapribogyót, és kb. 20 perc alatt készre főzzük. ', 'nincs'),
(18, 'Csokis muffin', 4, 'kep18.jpg', '15dkg - liszt	\r\n0.5csom	- sütőpor	\r\n15dkg - cukor	\r\n5dkg - cukrozatlan kakaópor	\r\n2db - tojás	\r\n15dkg - vaj	\r\n3ek - baracklekvár	\r\n5dkg - étcsokoládé', '- glutén\r\n- tojás\r\n- tej', '1. A csokis muffin elkészítéséhez egy tálban összekeverjük a száraz hozzávalókat: a lisztet, a sütőport, a cukrot és a kakaóport.\r\n2. Folyamatos keverés mellett hozzáadjuk a tojásokat, a megolvasztott vajat, a baracklekvárt, végül pedig a darabokra tört étcsokoládét.\r\n3. A tésztát egy 12 darabos, papírkapszlikkal kibélelt muffintepsibe adagoljuk, majd a 170 fokra előmelegített sütőben 20-25 perc alatt készre sütjük.', 'https://www.youtube.com/embed/l9dUjcnbUEM?si=JBmFsL4fKTef0aPY'),
(19, 'Töltött tök', 2, 'kep19.jpg', '1fej - vöröshagyma	\r\n2db - kisebb tök	\r\n2gerezd	- fokhagyma	\r\n1csok - kapor	\r\n2ek - olívaolaj	\r\nsó	\r\n80dkg - darált sertéshús	\r\n20dkg - főtt rizs	\r\n1tk - majoránna	\r\nbors	\r\n33dkg - tejföl	\r\n1dl - víz', '- tej', '1. A hagymát meghámozzuk, és apró kockákra vágjuk. A tököt meghámozzuk, félbevágjuk, és kikanalazzuk a magos, puha részét. A fokhagymát fokhagymanyomón átnyomjuk, a kaprot apróra vágjuk.\r\n2. Egy serpenyőben, egy evőkanál olívaolajon a hagymát alacsony hőmérsékleten 5-6 perc alatt üvegesre dinszteljük. Az elején megsózzuk, és ha már összeesett, hozzáadjuk a fokhagymát, 1-2 percig kevergetve pirítjuk, majd levesszük a tűzről.\r\n3. Egy keverőtálba rakjuk a darált húst, hozzáadjuk a dinsztelt hagymát, a főtt rizst, fűszerezzük a kapor egyharmadával, a majoránnával, ízesítjük sóval, borssal, az egészet jó alaposan összekeverjük.\r\n4. A sütőt előmelegítjük 180 fokra, egy magasabb falú tepsibe vagy jénaiba egy evőkanál olajat öntünk, megsózzuk. Erre helyezzük a tökhajókat, kicsit megmozgatjuk, hogy az olajat és a sót is eloszlassuk a tepsi alján, majd enyhén sózzuk a tetejét is. Azután a tököket megtöltjük a húsos keverékkel, kézzel formázzuk, és enyhén megnyomkodjuk, tömörítjük a tölteléket.\r\n5. Egy tálba rakjuk a tejfölt, hozzáadjuk a maradék kaprot, jól összekeverjük, és megkenjük vele a töltelék tetejét. Egy keveset hagyhatunk a tálaláshoz is.\r\n6. Vizet öntünk a tepsi aljára, lefedjük, majd az előmelegített sütőben 50 percig sütjük. 50 perc elteltével levesszük a tetejét, a sütő hőmérsékletét 200 fokra emeljük, és további 15 percig sütjük, vagy amíg a tejföl meg nem pirul a tetején.\r\n7. Az elkészült töltött tököt melegen tálaljuk, meglocsolhatjuk a megmaradt kapros tejföllel, fogyaszthatjuk rizzsel vagy friss kenyérrel.', 'https://www.youtube.com/embed/-vCNsE46vWo?si=5QfmQO__qkYfYjGd'),
(20, 'Fasírt', 1, 'kep20.jpg', '40dkg - darált sertéscomb	\r\n2fej - vöröshagyma	\r\n4gerezd	- fokhagyma	\r\n2db - tojás	\r\n2db - szikkadt zsemle	\r\nsó	\r\nőrölt - feketebors	\r\n2tk - fűszerpaprika	\r\nzsemlemorzsa	\r\nolaj a sütéshez', '- glutén\r\n- tojás\r\n- tej', '1. A fasírt elkészítéséhez megdinszteljük olajon az apró kockára vágott vöröshagymát. Ha egy kicsit kihűlt, hozzáadjuk a darált húshoz, rányomjuk a fokhagymát, majd a tojásokat is ráütjük.\r\n2. A szikkadt zsemléket tejbe áztatjuk néhány percre, aztán alaposan kifacsarjuk, és ezt is a húshoz adjuk.\r\n3. Fűszerezzük sóval, borssal és pirospaprikával a fasírtalapot, majd alaposan keverjük össze. Használjuk a kezeinket! Ha túl lágy lenne a massza, akkor adjunk hozzá egy kevés zsemlemorzsát is.\r\n4. Miután alaposan összekevertük a fasírtmasszát, vizes kézzel pici golyókat formázunk belőle, majd kevés zsemlemorzsában megforgatjuk. Így lesz jó ropogós a külsejük.\r\n5. Végül nem túl forró olajban, pár perc alatt kisütjük valamennyit. Krumplipürével, petrezselymes burgonyával vagy sült krumplival is tálalhatjuk. Adhatunk hozzá tejfölös-hagymás mártogatóst is.', 'https://www.youtube.com/embed/8bwK7T_dKJs?si=7udUbGygoF9DbpKp'),
(21, 'Hollandi mártás', 1, 'kep21.jpg', '25dkg - vaj	\r\n4db - tojássárgája	\r\n2ek - víz	\r\n1csip - só	\r\n0.5tk - fehérborecet	\r\n0.5db - citrom leve	\r\n1csip - cayenne bors', '- tojás\r\n- tej', '1. A vajat megolvasztjuk. A tojássárgájákat egy fém vagy üveg keverőtálba tesszük, és hozzáadunk 2 ek vizet, a sót és a borecetet, majd nem túl forró vízgőz fölé tesszük a tálat. (A tál alja ne érjen bele a forró vízbe!)\r\n2. Kézi vagy gépi habverővel keverni kezdjük és folyamatosan verjük, amíg fakó sárgává nem válik. Néha ellenőrizzük, hogy a gőz, amiben áll ne legyen se túl hideg, mert akkor nem lesz elég kemény a mártás, se túl meleg, mert akkor összecsomósodik.\r\n3. Lehúzzuk a tűzről, és folyamatos keverés mellett először cseppenként, majd kissé bátrabban hozzáadjuk az olvasztott vajat. Ha a mártás nagyon keménynek tűnik, hozzáadunk egy evőkanál vizet.\r\n4. A citromlével és a Cayenne-borssal ízesítjük, és ha szükséges, adunk hozzá még sót. Azonnal tálaljuk spárga vagy Benedict tojás mellé.', 'https://www.youtube.com/embed/JwoJPRt3Jh4?si=9wpIhZKqAev5ojuF'),
(22, 'Kapros lazactatár', 1, 'kep22.jpg', '30dkg - füstölt lazacszelet	\r\n10dkg - kígyóuborka	\r\n1csok - kapor	\r\n1tk - só	\r\nbors	\r\n0.5db - citrom	\r\n2ek - majonéz	\r\n1fej - lila hagyma	\r\ntoast kenyér', '- tojás\r\n- hal\r\n- mustár', '1. A kapros lazactatár elkészítéséhez a füstölt lazacszeleteket kicsomagoljuk, és apró kockákra vágjuk. Egy fém vagy üveg keverőtálba tesszük.\r\n2. A kígyóuborkát megmossuk, meghámozzuk és kis kockákra vágjuk, és szintén a keverőtálba öntjük.\r\n3. A felaprított kaprot, a sót, a borsot, a citrom kifacsart levét, a majonézt és a felaprított lila hagymát is hozzáadjuk, és összekeverjük mindet.\r\n4. Ha ezzel elkészültünk, nincs más dolgunk, mint pihentetni fél órát, és addig elkészíteni a pirítóst, melyet a lazactatárral megkenve remek előételt kapunk. ', 'https://www.youtube.com/embed/2Lh6oq4HgTs?si=J2Y-uTHdRdHXNCaI'),
(23, 'Rántott karfiol', 2, 'kep23.jpg', '1kg - karfiol	\r\n3db - tojás	\r\n2ek - tej	\r\n10dkg - liszt	\r\n20dkg - zsemlemorzsa	\r\nsó	\r\n3dl - olaj', '- glutén\r\n- tojás\r\n- tej', '1. A megtisztított karfiolt rózsáira bontjuk, megmossuk, a nagyobb rózsákat félbe és negyedbe vágjuk.\r\n2. Sós vízben forrástól számított 3 percig főzzük, majd leszűrjük, és lecsepegtetjük.\r\n3. Ha kihűlt, az összes karfiolrózsát lisztbe, majd tejjel elhabart tojásba, végül zsemlemorzsába forgatjuk. Ezután bő, forró olajban kisütjük mindet. Főtt rizs, vegyes saláta, sült krumpli illik mellé.', 'https://www.youtube.com/embed/0L8-ydYwfuc?si=JprmO7nVXh28apQJ'),
(24, 'Vadas marha', 2, 'kep24.jpg', '80dkg - fehérpecsenye	\r\nsó	\r\nbors	\r\nolaj	\r\n60dkg - zöldség	\r\n1fej - vöröshagyma	\r\n2gerezd	- fokhagyma	\r\n2db - babérlevél	\r\n1dl - száraz fehérbor	\r\n1ek - liszt	\r\n2dl - tejföl	\r\n1ek - cukor	\r\n1ek - mustár	\r\n0.5db - citrom leve	\r\n1ek - borecet', '- glutén\r\n- tojás\r\n- tej\r\n- mustár', '1. A húst felszeleteljük, a szeleteket kissé kiklopfoljuk, sózzuk, borsozzuk, és mindkét oldalukon, 2-3 evőkanál olajon hirtelen elősütjük 1-1 perc alatt.\r\n2. A hússzeleteket kiemeljük, a visszamaradt olajban a felkarikázott zöldségeket is megpirítjuk (kb. 5 perc), majd hozzáadjuk az apróra vágott vöröshagymát, fokhagymát, és kicsit lepirítjuk.\r\n3. Az elősütött húsokat rátesszük a zöldségágyra, rádobjuk a babérlevelet, sózzuk, borsozzuk, ráöntjük a fehérbort, valamint 1 dl vizet.\r\n4. Saját levében, fedő alatt, lassan pároljuk bő 1 óra hosszat. Ha kell, vízzel pótoljuk az elpárolgott levet.\r\n5. A megpuhult húsokat és a babért kiszedjük, a zöldségeket merülőmixerrel összeaprítjuk, a liszttel és a tejföllel behabarjuk a mártást.\r\n6. Cukorral, mustárral, tejföllel, citromlével, borecettel ízesítjük, a hússzeleteket visszahelyezzük a mártásba, és lassan jól átforraljuk.\r\n7. A krumpligombóchoz az összetört főtt burgonyát a többi alapanyaggal összedolgozzuk, majd a masszából dió nagyságú gombócokat formázunk, lobogó sós vízbe dobjuk, amikor feljönnek a víz tetejére, tálba szedjük, kevés olajjal meglocsoljuk, hogy ne ragadjanak össze.', 'https://www.youtube.com/embed/_GzxiPOAt9U?si=xFqyIP6_j83odDra'),
(25, 'Madeira sütemény', 4, 'kep25.jpg', 'Piskótához:\r\n3db - tojás	\r\n10dkg - margarin	\r\n12dkg - kristálycukor	\r\n1db - lime reszelt héja	\r\n0.5db - lime facsart leve	\r\n2.5dl - tej	\r\n30dkg - liszt	\r\n1csom - sütőpor	\r\n1csom - vaníliás cukor	\r\n1kvk - vaníliaaroma\r\n	\r\nKrémhez:\r\n25dkg - Mascarpone	\r\n1db', '- glutén\r\n- tojás\r\n- tej', '1. A piskótához felverjük a tojásokat, a margarint és a cukrot. Hozzákeverjük a lime reszelt héját, majd felváltva adagoljuk a tejet és a lisztet. Végezetül beledolgozzuk a sütőport, a vaníliás cukrot, a lime levét és a vaníliaaromát. Alaposan eldolgozzuk a tésztát.\r\n2. Egy 30 cm-es, püspökkenyér sütőformát olajjal vékonyan kikenünk, beletöltjük a tésztát és előmelegített sütőben, 170 Celsius-fokonon tűpróbáig sütjük.\r\n3. Ha kihűlt, hosszában kettévágjuk és hagyjuk teljesen kihűlni.\r\n4. A mascarponét a lime reszelt héjával és fél lime levével közepes fokozaton elkezdjük felverni, közben pedig lassan hozzáöntjük a cukrászhabot. Keményedésig verjük a krémet és csillag végű habzsákba töltjük.\r\n5. A habzsákból a sütemény alsó, vágott felére 6x3 db, kb. 4 cm magas halmocskát nyomunk körkörösen, majd a sorban 2-2 eperszeletet és 3-3 szem áfonyát nyomunk finoman a habba. Rátesszük a piskóta tetejét és ugyanezt megismételjük a sütemény tetején is, 2x5 halmocskával, 2-2 szelet eperrel és 3-3 áfonyával.\r\n6. Végül meghintjük egy kis reszelt citrommal, beletűzdelünk pár mentalevelet és fogyasztásig hűtőben tároljuk.', 'https://www.youtube.com/embed/inMXk3zCTTM?si=DK2Cxy6kyL90gcAA'),
(26, 'Rumos meggy parfé', 4, 'kep26.jpg', '15dkg - meggy kimagozva	\r\n2dl - rum	\r\n1.75dl - tejszín	\r\n2db - tojás	\r\n6dkg - porcukor	\r\n5dkg - hántolt mandula', '- tojás\r\n- tej\r\n- diófélék', '1. A kimagozott meggyet nagyobb darabokra vágjuk, és egy tálba téve ráöntjük a rumot. Lefedve legalább egy órát hagyjuk állni.\r\n2. A tejszín felét egy nyeles lábasban majdnem forrásig melegítjük. Közben a tojássárgákat a cukor felével fehéredésig habosítjuk egy kézi robotgéppel. A forró tejszínt kis adagokban a cukros tojássárgájára öntjük, miközben folyamatosan keverjük.\r\n3. A tejszínes-tojássárgás keveréket visszaöntjük a lábasba, és kevergetve lassú tűzön addig főzzük, míg besűrűsödik. A tűzről levéve hagyjuk teljesen kihűlni.\r\n4. A meggyet lecsepegtetjük, és a kihűlt pudinghoz adjuk. A rumot nem öntjük ki, hanem félretesszük. A mandulát durvára vágjuk, és ezt is a meggyes-tojásos masszához keverjük.\r\n5. Kibélelünk folpakkal egy félliteres, hosszúkás kenyérformát, úgy, hogy a fóliaszélek túllógjanak a forma peremén.\r\n6. Egy tálban kemény habbá verjük a tojásfehérjét, és egy másik tálban a megmaradt tejszínt is keményre verjük.\r\n7. Egy habverővel óvatosan a meggyes-mandulás krémbe forgatjuk a kétféle habot. A keveréket az előkészített formába öntjük, és két órára a fagyasztóba tesszük.\r\n8. Azután kivesszük a formát a fagyasztóból, átkeverjük a parfét, hogy a meggyszemek ne üljenek le a forma aljába, és visszatesszük a formát a fagyasztóba egy egész éjszakára.\r\n9. Tálalás előtt egy kanál porcukrot egy kis serpenyőbe teszünk a meggyes rummal együtt, és lassú tűzön addig forraljuk, míg egy nem túl sűrű szirupot kapunk. Hagyjuk kihűlni.\r\n10. Tálalás előtt 10 perccel kivesszük a parfét a fagyasztóból, és kifordítjuk egy deszkára. Lehúzzuk róla a fóliát, majd szeletekre vágjuk, és a sziruppal meglocsolva, valamint a friss, félbevágott meggyszemekkel díszítve tálaljuk.', 'https://www.youtube.com/embed/Bt3-CeNi-Rs?si=nMbC27At0VejVlD4'),
(27, 'Marhahúsleves', 3, 'kep27.jpg', '1.2kg - marhalábszár, -szegy vagy -rostélyos	\r\n60dkg - csont	\r\n1fej - hagyma	\r\n4gerezd	- fokhagyma	\r\n1körömnyi - cseresznyepaprika	\r\n15szem - bors	\r\n1kvk - sáfrány	\r\n80dkg - vegyes leveszöldség	\r\n30dkg - kelkáposzta	\r\n1csok - petrezselyem	\r\n1db - zöldpapr', 'nincs', '1. A húst és a csontot megmossuk, a húst 3-4 darabra vágjuk. A hagymát és a fokhagymát meghámozzuk, a cseresznyepaprikát leöblítjük, a borsot és a sárfrány(os szeklicé)t teatojásba zárjuk. A zöldségeket megtisztítjuk, és hasábokra vágjuk. A kelkáposztát, a csokorban hagyott petrezselymet, a zöldpaprikát és a paradicsomot leöblítjük.\r\n2. A csontot és a húst egy nagyobb fazék aljára tesszük, felöntjük 3 l hideg vízzel. Forrásig hevítjük, első habját szitakanállal leszedjük, majd hozzáadjuk a teatojást, a hagymát, a fokhagymát, a cseresznyepaprikát és egy kevés sót. Fedő nélkül, lassan gyöngyöző forralással fél óráig főzzük.\r\n3. A leveshez adjuk a vegyes zöldséget, a kelkáposztát, a csokorban hagyott petrezselymet, a zöldpaprikát és a paradicsomot egészben, majd további lassú forralással, fedő nélkül az egészet puhára főzzük.\r\n4. Enyhén sós vízben kifőzzük a finommetéltet, leszűrjük, rámerünk egy kevés húslevest, melegen tartjuk.\r\n5. A húsleves felszínéről leszedjük a zsiradékot. A levest merőkanállal előmelegített tálba szedjük-szűrjük, hozzáadjuk a tésztát. A zöldséget és a húst előmelegített tálra rendezzük, és a levessel együtt vagy utána, tetszés szerinti mártásokkal tálaljuk.', 'https://www.youtube.com/embed/t6GHdkk3Im4?si=O_vjLoqFVfxSGTWA'),
(28, 'Ramen', 3, 'kep28.jpg', '30dkg - csirkemell	\r\n10g - shitake gomba (szárított)	\r\n4db - tojás	\r\n3db - leveskocka	\r\n2gerezd	- fokhagyma	\r\nkh - gyömbér	\r\n1csom - újhagyma	\r\nízlés szerint só	\r\nízlés szerint bors	\r\n4ek - szójaszósz	\r\n1ek - fehér ecet	\r\n1dl - olaj	\r\n2.5l - víz', '- szójabab', '1. A csirkemelleket csíkokra vágjuk, majd kevés olajon megpirítjuk. Felöntjük a vízzel, sózzuk, és kb. 30 percig főzzük úgy, hogy a hozzáöntött vízből kb. 1,5 liter maradjon.\r\n2. A húst kivesszük a léből, tányérra helyezzük és letakarjuk.\r\n3. Az erőlevesbe belemorzsoljuk a leveskockákatt és felforraljuk. Ha kész, levesszük a tűzről.\r\n4. Az újhagymát, a gyömbért, a fokhagymát megpucoljuk, apróra vágjuk. A szárított gombát is aprítjuk.\r\n5. Egy lábasban olajat melegítünk, hozzáadjuk az aprított zöldségeket, és egy picit megpirítjuk. A zöldségre ráöntjük az erőlevest, és további 15 percig főzzük.\r\n6. Hozzáadjuk a szójaszószt és a fehérecetet, majd ismét felforraljuk. Végül visszatesszük a csirkemellet is, még egyet rottyantunk rajta, és kész is.\r\n7. A tojásokat kb. 5 perc alatt megfőzzük. Eltávolítjuk a héját, félbe vágjuk.\r\n8. A levest tányérokba szedjük, és a főtt tojással tálaljuk.', 'https://www.youtube.com/embed/XmbsOmel_Yg?si=kjzmAvAzDzVPgRRk'),
(29, 'Színes rizssaláta', 5, 'kep29.jpg', '3db - cékla	\r\n14dkg - rizs-vadrizs keverék	\r\nsó	\r\n2marék - konyhakész bébispenót	\r\n1marék - dióbél	\r\nfrissen - őrölt bors	\r\n10dkg - feta sajt	\r\n\r\nAz öntethez:\r\n2ek - balzsamecet	\r\n1ek - méz	\r\n1.5ek - olívaolaj	\r\nsó	\r\nfrissen - őrölt bors', 'nincs', '1. A céklákat megmossuk, majd egyesével alufóliába csomagoljuk, és 200 fokos sütőben legalább 60 percig sütjük, vagy amíg meg nem puhulnak. A sütőből kivéve eltávolítjuk a fóliát, és hagyjuk hűlni őket, majd meghámozzuk, és falatnyi kockákra vágjuk.\r\n2. Egy szűrőbe téve többször átmossuk rizskeveréket. Ezután feltesszük főni bő, sós vízben. Felforraljuk, majd fedő alatt, alacsony lángon puhára főzzük kb. 45 perc alatt, vagy amíg meg nem puhul. Ha ezzel elkészültünk, leszürjök, és hagyjuk kihűlni.\r\n3. Közben az öntet hozzávalóit egy zárható üvegcsébe tesszük, és alaposan összerázzuk. Ezt követően a hűtőbe tesszük a felhasználásig.\r\n4. Összeállítjuk a salátát. A kihűlt rizst összeforgatjuk a céklával, a bébi- spenóttal és a durvára tört, száraz serpenyőben megpirított dióval vagy kesudióval. Az öntetet a salátára öntjük, sózzuk és borsozzuk, majd lazán összeforgatjuk. Ezután hűőbe tesszük, hogy az ízek összeérjenek. Tálaláskor rámorzsoljuk a fetát. Szobahőmérsékletűen kínáljuk önmagában, vagy natúr sült húsok mellé.', 'https://www.youtube.com/embed/u-Xp9MnvEx8?si=zHDXprs_IeEC7rVw'),
(30, 'Tzatziki Görög joghurttal', 5, 'kep30.jpg', '1db - kígyóuborka	\r\nsó	\r\n40dkg - natúr görög joghurt	\r\n1gerezd - fokhagyma	\r\n0.5db - citrom	\r\nbors	\r\nolívaolaj', '- tej', '1. Az uborkát megmossuk és szárazra töröljük, majd a reszelő durva oldalán lereszeljük. (Az uborkát egyébként meg is hámozhatjuk reszelés előtt, ez igazából már csak ízlés kérdése.)\r\n2. Az összezúzott fokhagymát jól összekeverjük a görög joghurttal, majd pár csepp citromlével ízesítjük. Ha lehet, frissen facsarjuk rá.\r\n3. Ezután nincs más dolgunk, mint hozzáadni a lecsepegtetett uborkát a joghurthoz, és ízlés szerint megborsozni, majd jól elkeverni.\r\n4. Húsok mellé tálalva kiváló saláta, köret lehet. Pici olívaolajjal meglocsolva kínáljuk. Természetesen a tzatziki tökéletesen illik gyros mellé is.', 'https://www.youtube.com/embed/EdhJn9mSYOw?si=dT_V0ujIgQhfn6jH');

-- --------------------------------------------------------

--
-- Tábla szerkezet ehhez a táblához `eteltipusok`
--

CREATE TABLE `eteltipusok` (
  `eteltipusok_id` int(11) NOT NULL,
  `eteltipusok_nev` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_hungarian_ci;

--
-- A tábla adatainak kiíratása `eteltipusok`
--

INSERT INTO `eteltipusok` (`eteltipusok_id`, `eteltipusok_nev`) VALUES
(1, 'előételek'),
(2, 'főételek'),
(3, 'levesek'),
(4, 'desszertek'),
(5, 'saláták');

--
-- Indexek a kiírt táblákhoz
--

--
-- A tábla indexei `etelek`
--
ALTER TABLE `etelek`
  ADD PRIMARY KEY (`etelek_id`),
  ADD KEY `etelek_tipus` (`etelek_tipus`);

--
-- A tábla indexei `eteltipusok`
--
ALTER TABLE `eteltipusok`
  ADD PRIMARY KEY (`eteltipusok_id`);

--
-- A kiírt táblák AUTO_INCREMENT értéke
--

--
-- AUTO_INCREMENT a táblához `etelek`
--
ALTER TABLE `etelek`
  MODIFY `etelek_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=44;

--
-- AUTO_INCREMENT a táblához `eteltipusok`
--
ALTER TABLE `eteltipusok`
  MODIFY `eteltipusok_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;

--
-- Megkötések a kiírt táblákhoz
--

--
-- Megkötések a táblához `etelek`
--
ALTER TABLE `etelek`
  ADD CONSTRAINT `etelek_ibfk_1` FOREIGN KEY (`etelek_tipus`) REFERENCES `eteltipusok` (`eteltipusok_id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
